### PR TITLE
Scp 106

### PR DESCRIPTION
**Pull request by JCGWE30**
SCP 106

### CODE REVIEW

**Comment by NexusLeader** [comment]
lookin like it has some issues with your draftmap

**Comment by NexusLeader** [comment]
ze rest? OH MY GAWD!!

**Comment by NexusLeader** [comment]
@JCGWE30 build n test debug failing

**Comment by JCGWE30** [comment]
Do not merge this yet it is still a draft

**Review by NexusLeader — APPROVED** [review]
dis good

**Comment by JCGWE30** [comment]
Il fix this in a bit

**Comment by JCGWE30** [comment]
@NexusLeader ready to merge

**Pull request merged**
