### PR TITLE
News Jobs Icons

### PR DESCRIPTION
**Pull request by Ozzy-Land**
## About the PR
Added job icons

## Why / Balance
NA

## Technical details
Simple

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by NexusLeader** [comment]
beep boop you are fired

**Comment by NexusLeader** [comment]
checks unsuccessful fix first  
image

**Comment by NexusLeader** [comment]
Soon, soon we willl evolve from C#!!!!

**Comment by Ozzy-Land** [comment]
working on prototypes, testing before pulling is lame anyways :clueless:

**Comment by NexusLeader** [comment]
Being fixed with new PRs. Closed

**Pull request closed without merging**
